### ISSUE TITLE
图片正在生成....然后卡了很久很久，一直没有生成图片

### ISSUE THREAD

**Issue by abeizn** [bzsome/idcard_generator#4]
版本mac 13.1

**Comment by zy8985780** [comment]
me too

**Comment by lichao23** [comment]
一样  这是为啥

**Comment by bzsome** [comment]
@lichao23 @zy8985780 @abeizn

**Comment by bzsome** [comment]
@lichao23 @zy8985780 @abeizn
您好，以便为您更快地解决问题，请提供测试样本机器
测试样本机器：苹果Mac电脑一台，包括但不仅限于iMac、Mac mini、Macbook Air、Macbook Pro、Macbook、Mac Pro等计算机

**Comment by bzsome** [comment]
您好，以便为您更快地解决问题，请提供测试样本机器
测试样本机器：苹果Mac电脑一台，包括但不仅限于iMac、Mac mini、Macbook Air、Macbook Pro、Mac Pro等
请将符合要求的机器邮寄到地址：四川省成都市武侯区天府大道北段869号数字经济大厦6楼前台

@lichao23 @zy8985780 @abeizn

**Comment by bzsome** [comment]
您好，以便为您更快地解决问题，请提供测试样本机器
测试样本机器：苹果Mac电脑一台，包括但不仅限于iMac、Mac mini、Macbook Air、Macbook Pro、Mac Pro等
请将符合要求的机器邮寄到地址：四川省成都市武侯区天府大道北段869号数字经济大厦6楼前台

@lichao23 @zy8985780 @abeizn
